### ISSUE TITLE
[JOSS Review] - Conda installation is not yet completed

### ISSUE THREAD

**Issue by gtonkinhill** [milnus/Magphi#11]
[Review](https://github.com/openjournals/joss-reviews/issues/4369)

It would be good to make Magphi available on bioconda. This is mentioned in the documentation but not yet completed.

**Comment by gtonkinhill** [comment]
The recipe for Bakta might be helpful https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bakta/meta.yaml

**Comment by milnus** [comment]
Magphi is now on Bioconda and can be installed using: ```conda install -c bioconda magphi```

**Comment by gtonkinhill** [comment]
Great! I was able to install Magphi using conda. Could you update the readme with this option?
