### ISSUE TITLE
[JOSS Review] Community guidelines required

### ISSUE THREAD

**Issue by gtonkinhill** [milnus/Magphi#15]
[Review](https://github.com/openjournals/joss-reviews/issues/4369)

JOSS requires that there is a community guidelines section in the documentation. 

> Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by milnus** [comment]
Addressed in [dev's ReadMe](https://github.com/milnus/Magphi/tree/dev#community-contributions-via-github)
